
runtime: nodejs18
env_variables:
  PAYSTACK_SECRET_KEY: sk_live_ef048728ce1a346896add6ae46237e6155b850e1
  TYPEORM_CONNECTION: mysql
  TYPEORM_URL: 
  NODE_ENV: production
  MYSQL_DATABASE: buzzz
  MYSQL_USER: root
  MYSQL_PASSWORD: cd1228ac
  MYSQL_HOST: /cloudsql/buzzz-server:europe-west2:buzzz-db
  APP_URL: https://buzzz-server.ew.r.appspot.com/
  CLIENT_URL: https://www.yourbuzzz.com
  DESIGN_CLIENT_URL: https://design.yourbuzzz.com
  DEBUG_CLIENT_URL: http://localhost:3000
  DEBUG_DESIGN_CLIENT_URL: http://localhost:5500
  CLOUD_SQL_CONNECTION_NAME: buzzz-server:europe-west2:buzzz-db
  TYPEORM_HOST: /cloudsql/buzzz-server:europe-west2:buzzz-db
  TYPEORM_DATABASE: buzzz
  TYPEORM_USERNAME: root
  TYPEORM_PASSWORD: cd1228ac
  UNIX_SOCKET_PATH: /cloudsql/buzzz-server:europe-west2:buzzz-db
  TYPEORM_PORT: 3306
  TYPEORM_SYNCHRONIZE: false
  TYPEORM_ENTITIES: src/**/entities/*.ts
  TYPEORM_MIGRATIONS: src/database/migrations/*.tsx
  TYPEORM_MIGRATIONS_DIR: src/database/migrations
  JWT_SECRET: a2c55651808d1535941djsjddb
  JWT_EXPIRE: 10m
  REFRESH_JWT_SECRET: j5gdfb664734gf704yfgs34fg740
  REFRESH_JWT_EXPIRE: 1d
  JWT_COOKIE_EXPIRE: 1hr
  OAUTH_GOOGLE_ID: 652901500016-vi3l11sqha5j7u1smf58c3fovik20gsb.apps.googleusercontent.com
  OAUTH_GOOGLE_SECRET: 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
  OAUTH_TWITTER_CONSUMER_KEY: EsInz8fX9ejb7YaSGHQVM2NP5
  OAUTH_TWITTER_CONSUMER_SECRET: q6yMELgUxz2agjlCjU8QUfZ7hqT7sDuUymxy4Mvxtvs6sDMN59
  SENDGRID_API_KEY: 
  SMTP_HOST: mail.privateemail.com
  ADMIN_CLIENT_URL: https://www.admin.yourbuzzz.com
  SMTP_PORT: 465
  SMTP_EMAIL: hello@yourbuzzz.com
  SMTP_PASSWORD: ehindero1972
  FROM_EMAIL: hello@yourbuzzz.com 
  FROM_NAME: Buzzz
  PORT: 500
  FIREBASE_DATABASE_URL: https://buzzz-37d26-default-rtdb.firebaseio.com/
  FIREBASE_IMAGE_URL: https://buzzz-chi.vercel.app/svg/logo.svg
  TYPE: service_account
  PROJECT_ID: buzzz-37d26
  PRIVATE_KEY_ID: a2c55651808d15359418ce981204a00a3fa1257e
  PRIVATE_KEY: '-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDQPUtbeqCPfiJn
Sro5IfuvWGm2NbCdcBHBRP4LP73tdObHxl9Z6R/FIjVHewaMxtzbGpw73zP9HY2L
nOgTyHdQ6u8zS6MzFeUAnYinIaxedw8BGQPMqEYbUnU1t1aLRTdDDLZVoeU9Mk4l
m2MpzApG1JTH0ZvVWm5PAgFEExeb7xTS+Dk/ciKfDCqS6wuR2jYB0vtPP2Bu00EG
fvMMUd7zUCh4sF93iJ+QFo/Z2UAk4CXFpYWRvZTmNCJoFUjdUC/z5h9HZDAKVkQk
m6JOTNPBDPT3PfjvDvprP9aSp9ii+xbYI0kzgSVEoEllo/RbSgqJvKPDDuDnGSkz
4V77uT3ZAgMBAAECggEABE7MTQlpomZJ2Gitlwp6risuTqhoLa2YlG60sa9hIrUp
JAdYyB+gOmAFiaPEJCvl/Dtd8Yghx3Hx0GpPy775JumhRqahKuigSuW3Yru52N9u
Jkfp8fUmNCD9zz1qcymcpcywxe86MoyknLcM81um98WkiUivCFgdUZGZTJr3gVCE
iGxwgD7FT+q6VaZHy2Jx5F2FGXRuTM0bh45MvPRImx3sfy3bDSms4Q6jsK3HIve4
Yk/wwghSyU9SKUhkfNoiX/jOwOzGQez5dL/xBdkoS3fIf7yBrn5fAfpOjkxAtz8O
IYFU9X93sRqbIKOahmtr7fHPWWWOF4G50LrNbaxBIQKBgQDoqXpcc3Jh7Py9MCwA
QSTQQvtX8ZC1LCnwkzwNX6XVfg0VflsFhGbjGgUJd22479a+W6Lx8DqYpfQjxops
nl8gZ8V4zEz8+HGp311QSKrdQKJxA05W1hqTAaNUjNzWjKjYDf67dcBcacN9Mdzr
jdA1AHWiA87jp3UfqU8d0gbQsQKBgQDlIKtWISe5xJrTzKfUSemyccVgPkjL+k+/
ozU/CQz8x0D5wA+5xm6IcXBQ1u5rQwlulVTYFdAPcFU+MslDZIrE2M2qizraYOt4
SWq8v39JUzmRl4FHvpeAacm5qLz8O9iqOEg/mYMxErLVsRER9M8R8DyEzND2TC9U
XyqbVOdJqQKBgBrXmrdZ1mN33PzStvDckyu33pmZ1BEi5D/OLMp6M367CTVmm4e6
a8hdsyERd0Yz3XmexuDUz13XH6CVAllfuCfb8QtrvqIc47gufeyKRbQ7BcK2F+6q
yuwU70wM6FmUZtJuYuorvqKqzRP/kbZXaSMER44GlHLtWfTqKqeNGJ4xAoGAblQF
zIpYe54Mw3GnWpRgoFkiJk63dOjJ38gxynGMPGehhOETcWv4K2EcKQDleuajswja
+tW+AsEferyvpvDR1SlkFvvF0gObPqdzawF2xBL8BHwEd0xx3RaTWP/ESFx03roN
J/q+bjHHxRfm1VOhJc0dBwEsmXxjyeetN3BxkkkCgYBhqIzzaP7Chu/+bsqus9fK
70SSl8+C3I/+Gcs9xxwRWIMht3rL+qAVXHmWwUB8eK1rr+WiFNrLo5F6p6ODu1e4
KlEsa/BmfJoY3ln+MatSlWDo1TzOIojDL8PSCP9dPe867+LlbegTp+7hCEaabi6w
4lMT8IbJHxKm20i4tXWJlQ: : 
-----END PRIVATE KEY-----
'
  CLIENT_EMAIL: firebase-adminsdk-q00my@buzzz-37d26.iam.gserviceaccount.com
  CLIENT_ID: 115397941695726707258
  AUTH_URI: https://accounts.google.com/o/oauth2/auth
  TOKEN_URI: https://oauth2.googleapis.com/token
  AUTH_PROVIDER_X509_CERT_URL: https://www.googleapis.com/oauth2/v1/certs
  CLIENT_X509_CERT_URL: https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-q00my%40buzzz-37d26.iam.gserviceaccount.com
  CLOUD_NAME: eddymadu
  CLOUD_API_KEY: 287241113588159
  CLOUD_API_SECRET: x_gCfnDAWufLrUlziXdxVqbbAYY 
  CLOUDINARY_URL: cloudinary://287241113588159:x_gCfnDAWufLrUlziXdxVqbbAYY@eddymadu
  PASSPORT_SESSION_SECRET: e78QnSupNIISEy9ETFiqpLX9HC0b85Vt
  REDIS_HOST : 10.227.168.75
  REDIS_PORT : 6379
  SUPER_EMAIL : admin@yourbuzzz.com
  SUPER_PASSWORD : buzzz123098@yourbuzzz

instance_class: F2

  # This section is for App Engine's automatic scaling settings
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10
  

# This section is for App Engine's health check settings
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# This section is for handling static files or assets
handlers:
- url: /static
  static_dir: ./static

- url: /.*
  script: auto
  
beta_settings:
  cloud_sql_instances: buzzz-server:europe-west2:buzzz-db:500