
services:
  redis: 
    image:  redis:7.0-alpine
    ports:
      - '6379:5000'
    restart: always
    volumes:
      - ./redis_store:/var/lib/redis
  
  db: 
    image:  mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'    
    restart: always
    environment:
      - MYSQL_DATABASE=buzzzz
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=root
    volumes:
      - ./store:/var/lib/mysql
  
  buzzz:
    restart: always
    build: ./
    container_name: buzzz
    hostname: buzzz
    volumes:
      - ./buzzz:/var/lib/buzzz
    ports:
      - '81:5000'
    depends_on:
    - redis
    - db

 