
services:
  redis: 
    image:  redis:7.0-alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis_data:/var/lib/redis
  
  db: 
    image:  mysql:8.0
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'    
    restart: always
    environment:
      - MYSQL_DATABASE=buzzzz
      - MYSQL_ALLOW_EMPTY_PASSWORD= 1
    volumes:
      - mysql_data:/var/lib/mysql
  
  buzzz:
    restart: always
    build: ./
    container_name: buzzz
    hostname: buzzz
    volumes:
      - .:/usr/buzzz-server/
    ports:
      - '5000:5000'
    depends_on:
    - redis
    - db

volumes:
  mysql_data:
  redis_data:
    

 