

ARG UNIX_SOCKET_PATH
ARG CLOUD_SQL_CONNECTION_NAME

ARG JWT_SECRET
ARG JWT_EXPIRE
ARG REFRESH_JWT_SECRET
ARG REFRESH_JWT_EXPIRE
ARG JWT_COOKIE_EXPIRE

ARG OAUTH_GOOGLE_ID
ARG OAUTH_GOOGLE_SECRET
ARG OAUTH_TWITTER_CONSUMER_KEY

ARG OAUTH_TWITTER_CONSUMER_SECRET
ARG SENDGRID_API_KEY
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_EMAIL
ARG SMTP_PASSWORD
ARG FROM_EMAIL
ARG FROM_NAME
ARG PORT
# firebase
ARG FIREBASE_DATABASE_URl
ARG FIREBASE_IMAGE_URL
ARG TYPE
ARG PROJECT_ID
ARG PRIVATE_KEY_ID
ARG PRIVATE_KEY
ARG CLIENT_EMAIL
ARG CLIENT_ID
ARG AUTH_URI
ARG TOKEN_URI
ARG AUTH_PROVIDER_X509_CERT_URL
ARG CLIENT_X509_CERT_UR
# cloudinary
ARG CLOUD_NAME
ARG CLOUD_API_KEY
ARG  CLOUD_API_SECRET
ARG CLOUDINARY_URL
ARG PASSPORT_SESSION_SECRET
ARG SUPER_EMAIL
ARG SUPER_PASSWORD
# BUILD FOR PRODUCTION
FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json .

COPY tsconfig.build.json .

COPY tsconfig.json .

RUN yarn 

RUN yarn build

COPY . .


# PRODUCTION
FROM node:16-alpine AS production

WORKDIR /app

ENV PAYSTACK_SECRET_KEY=$PAYSTACK_SECRET_KEY
ENV TYPEORM_CONNECTION=$TYPEORM_CONNECTION
ENV TYPEORM_URL=$TYPEORM_URL
ENV NODE_ENV=$NODE_ENV
ENV APP_URL=$APP_URL
ENV CLIENT_URL=$CLIENT_URL
ENV DESIGN_CLIENT_URL=$DESIGN_CLIENT_URL
ENV DEBUG_CLIENT_URL=$DEBUG_CLIENT_URL
ENV DEBUG_DESIGN_CLIENT_URL=$DEBUG_DESIGN_CLIENT_URL
ENV TYPEORM_HOST=$TYPEORM_HOST
ENV TYPEORM_DATABASE=$TYPEORM_DATABASE
ENV TYPEORM_USERNAME=$TYPEORM_USERNAME
ENV TYPEORM_PASSWORD=$TYPEORM_PASSWORD
ENV TYPEORM_PORT=$TYPEORM_PORT
ENV TYPEORM_SYNCHRONIZE=$TYPEORM_SYNCHRONIZE
ENV TYPEORM_ENTITIES=$TYPEORM_ENTITIES
ENV TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS
ENV TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR
ENV UNIX_SOCKET_PATH=$UNIX_SOCKET_PATH
ENV CLOUD_SQL_CONNECTION_NAME=$CLOUD_SQL_CONNECTION_NAME

ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRE=$JWT_EXPIRE
ENV REFRESH_JWT_SECRET=$REFRESH_JWT_SECRET
ENV REFRESH_JWT_EXPIRE=$REFRESH_JWT_EXPIRE
ENV JWT_COOKIE_EXPIRE=$H=JWT_COOKIE_EXPIRE

ENV OAUTH_GOOGLE_ID=$OAUTH_GOOGLE_ID
ENV OAUTH_GOOGLE_SECRET=$OAUTH_GOOGLE_SECRET
ENV OAUTH_TWITTER_CONSUMER_KEY=$OAUTH_TWITTER_CONSUMER_KEY

ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PASSWORD
ENV SMTP_EMAIL=$SMTP_EMAIL
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV FROM_EMAIL=$FROM_EMAIL
ENV FROM_NAME=$FROM_NAME
ENV PORT=${PORT:-8080}

# firebase
ENV FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
ENV FIREBASE_IMAGE_URL=$FIREBASE_IMAGE_URL
ENV TYPE=$TYPE
ENV PROJECT_ID=$PROJECT_ID
ENV PRIVATE_KEY_ID=$PRIVATE_KEY_ID
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV CLIENT_EMAIL=$CLIENT_EMAIL
ENV CLIENT_ID=CLIENT_ID
ENV AUTH_URI=$AUTH_URI
ENV TOKEN_URI=$TOKEN_URI
ENV AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL
ENV CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL
ENV CLOUD_NAME=$CLOUD_NAME
ENV CLOUD_API_KEY=$CLOUD_API_KEY
ENV  CLOUD_API_SECRET=$CLOUD_API_SECRET 
ENV CLOUDINARY_URL=$CLOUDINARY_URL
ENV PASSPORT_SESSION_SECRET=$PASSPORT_SESSION_SECRET
ENV SUPER_EMAIL=$SUPER_EMAIL
ENV SUPER_PASSWORD=$SUPER_PASSWORD

COPY --from=build /app/node_modules ./node_modules

COPY --from=build /app/ ./
RUN yarn build


CMD [ "node", "dist/main.js" ]
