"use strict";
exports.__esModule = true;
exports.BASE_URL = exports.FRONTEND_URL = exports.DEFAULT_POLYMAILER_CONTENT = exports.SOCKET_CONNECT = exports.DESIGN_ERROR = exports.DESIGN_MERCH = exports.EVENT_QUEUE = exports.APP_GATEWAY = exports.JWT = exports.TEXT_TYPE = exports.IMAGE_TYPE = exports.PAYSTACK_SUCCESS_MESSAGE = exports.USERNAME_GENERATOR = exports.PUSH_NOTIFICATION = exports.AUTH_APP_NAME = exports.CLOUDINARY = exports.QRCODE = exports.AUTHENTICATOR = exports.EMAIL_PROVIDER = exports.PASSWORD_RESET_TOKEN_EXPIRY = void 0;
exports.PASSWORD_RESET_TOKEN_EXPIRY = 5 * 60 * 1000;
exports.EMAIL_PROVIDER = 'EMAIL_PROVIDER';
exports.AUTHENTICATOR = 'AUTHENTICATOR';
exports.QRCODE = 'QRCODE';
exports.CLOUDINARY = 'CLOUDINARY';
exports.AUTH_APP_NAME = 'BUZZZ';
exports.PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
exports.USERNAME_GENERATOR = 'USERNAME_GENERATOR';
exports.PAYSTACK_SUCCESS_MESSAGE = 'Verification successful';
exports.IMAGE_TYPE = "image";
exports.TEXT_TYPE = "i-text";
exports.JWT = 'JWT';
exports.APP_GATEWAY = 'APP_GATEWAY';
exports.EVENT_QUEUE = "event_queue";
exports.DESIGN_MERCH = "design_merch";
exports.DESIGN_ERROR = 'design_error';
exports.SOCKET_CONNECT = 'socket_connect';
exports.DEFAULT_POLYMAILER_CONTENT = "Idan!!! your face show your shoe shine";
exports.FRONTEND_URL = "buzzz-chi.vercel.app/";
exports.BASE_URL = 'http://localhost:5000';
